### ISSUE TITLE
Support a strict mode

### ISSUE THREAD

**Issue by sunesimonsen** [itsmepetrov/classnames-loader#1]
It would be nice if this module was able to throw an error if you try to use a css class that does not exists. This should of cause be an optional mode, by providing a query parameter: 

``` js
{
  test: /\.css$/,
  loaders: ['classnames?strict', ExtractTextPlugin.extract('style', 'css')])
}
```

If you think this is a viable feature, I'll be happy to create a PR for it.

Kind regards
Sune

**Comment by itsmepetrov** [comment]
Hi, @sunesimonsen,

I think it's a good idea, PRs are welcome)

**Comment by sunesimonsen** [comment]
Awesome, I'll take a look at it. I'll see if I can get it done this week.

Kind regards
Sune

**Comment by sunesimonsen** [comment]
I found out that I don't need it, so I'll just close the issue.
