### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by mrchief** [itsmepetrov/classnames-loader#9]
I see no recent updates and no support for webpack 3/4.

**Comment by js2me** [comment]
@mrchief which problems with webpack 4 do you have?
See my config for .scss files
```
 {
        test: /\.scss$/,
        use: [
          { loader: 'classnames-loader' },
          { loader: 'style-loader' },
          {
            loader: 'css-loader',
            query: {
              modules: true,
              sourceMap: !optimize,
              minimize: optimize,
              importLoaders: 2,
              localIdentName: '[local]__[hash:base64:5]',
            },
          },
          {
            loader: 'sass-loader',
            options: {
              sourceMap: !optimize,
              includePaths: [path.resolve(sourcePath, './global_styles')],
            },
          },
        ],
      },
```
and in modules I do
` import cx from './index.scss' `
And it works fine

**Comment by mrchief** [comment]
I don't remember the exact problem I was having anymore but my setup was CSS/PostCSS and no SCSS. I think hot-reloading or something at a very basic level was failing. I'll try to see if I can find any details.

**Comment by itsmepetrov** [comment]
Currently I don't have enough time to maintain this project but I'm open to review PRs and so on, so if you are interested in this project and ready to add support for new features I can give you access for the repo.

**Comment by mrchief** [comment]
I guess that answers my question. I'm going to close this issue for now. If I run into any errors, I'll open a new ticket with proper details. Thanks @js2me, @itsmepetrov  

> Currently I don't have enough time to maintain this project but I'm open to review PRs and so on, so if you are interested in this project and ready to add support for new features I can give you access for the repo.

It's a deal @itsmepetrov !
